{
	"version": 1602287524,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/beanperson-sheet0.png",
		"images/beanperson-sheet1.png",
		"images/wall-sheet0.png",
		"images/tiledbackground.png",
		"images/coneofvision-sheet0.png",
		"images/plainface-sheet0.png",
		"images/joystickbacking-sheet0.png",
		"images/joystick-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"c2mp-net.js",
		"c2mp-peer.js",
		"c2mp.js",
		"waker.js",
		"penumbra.png",
		"pathfind.js"
	]
}